[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
# All the following settings are optional:
where = ["."]  # ["."] by default
include = ["*"]  # ["*"] by default
exclude = ["inputs*", "outputs*", "docs*"]
namespaces = true  # true by default

[project]
name = "stream-dse"
version = "0.0.8"
description = "Stream - Multi-core accelerator design space exploration with layer-fused scheduling"
readme = "README.md"
authors = [{ name = "Arne Symons", email = "arne.symons@kuleuven.be" }, { name = "Linyan Mei", email = "linyan.mei@kuleuven.be" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
]
keywords = ["stream", "multi-core", "accelerator", "layer-fused", "scheduling", "zigzag", "dse", "design-space-exploration", "machine-learning", "deep-learning", "mapping"]
dependencies = [
    "zigzag-dse==3.8.2",
    "rtree",
    "deap",
    "matplotlib",
    "brokenaxes",
    "plotly",
    "pandas",
    "cerberus",
    "pre-commit",
    "gurobipy",
    "pydot",
    "xdsl-aie @ git+https://github.com/xdslproject/xdsl-aie.git@378c4c69c7f643ec31c6ef96c2fd830a0fb87244",
    "snax-mlir @ git+https://github.com/kuleuven-micas/snax-mlir.git@1c01c5d100df128c9fa01d3336ebea98e19b20cf",
    "snakemake",
    "openai",
]
requires-python = ">=3.11"


[project.optional-dependencies]
dev = ["bumpver", "pip-tools", "build", "twine", "pre-commit"]

[project.urls]
Homepage = "https://github.com/ZigZag-Project/stream"

[project.scripts]
realpython = "stream.__main__:main"

[tool.bumpver]
current_version = "0.0.8"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"'
]
"stream/__init__.py" = ["{version}"]


[tool.ruff]
target-version = "py311"
line-length = 120
fix = true
lint.select = ["E", "F", "W", "I", "PL", "N", "UP", "B"]
lint.ignore = ["D401", "N806"]
lint.pylint.max-args = 8
